[settings]
experimental = true

[tools]
usage = "latest"
"pipx:uv" = "latest"
"node" = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:opencode-ai" = "latest"
"npm:@github/copilot" = "latest"
"npm:apify-cli" = "latest"
