[settings]
experimental = true
npm.package_manager = "bun"

[tools]
node = "lts"
pnpm = "10"
bun = "1.3"

gh = "latest"
claude = "latest"
gemini = "latest"
codex = "latest"
opencode = "latest"
usage = "latest"
hcloud = "latest"

"npm:@github/copilot" = "latest"
"npm:openskills" = "latest"
"npm:apify-cli" = "latest"
"npm:@hona/ralph-cli" = "latest"

"pipx:ty" = "latest"
"pipx:mistral-vibe" = "latest"
