[settings]
experimental = true
npm.package_manager = "bun"

[tools]
python = "3.14"
node = "lts"
pnpm = "10"
bun = "1.3"
uv = "0.9"

gh = "latest"
claude = "latest"
gemini = "latest"
codex = "latest"
usage = "latest"
hcloud = "latest"

"github:anomalyco/opencode" = "latest"

"npm:@github/copilot" = "latest"
"npm:apify-cli" = "latest"
"npm:@hona/ralph-cli" = "latest"

"pipx:ty" = "latest"
"pipx:mistral-vibe" = "latest"
