[settings]
experimental = true

[tools]
usage = "latest"
"pipx:uv" = "latest"
"node" = "lts"
"claude" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"github:anomalyco/opencode" = "latest"
"npm:@github/copilot" = "latest"
"pipx:mistral-vibe" = "latest"
"npm:openskills" = "latest"
"npm:apify-cli" = "latest"
pnpm = "10"
bun = "1.3"
gh = "latest"
"pipx:ty" = "latest"
hcloud = "latest"
